networks:
  # The presence of these objects is sufficient to define them
  rama: {}

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:1.0.0
    networks:
      - rama
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: backend:1.0.0
    command: sh -c "sleep 5 && node /opt/backend/index.js"
    networks:
    - rama
    depend_on:
    - mysql
    container_name: backend

  frontend:
    image: frontend:1.0.0
    networks:
    - rama
    container_name: frontend
    ports:
    - 80:80
    depend_on:
    - backend
  